import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "../sass/main.scss";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <span id={styles["links-wrapper"]}>
          <span>
            GitHub Repo:
            <a href="http://mrklouie.tech/" target="_blank">
              http://mrklouie.tech/
            </a>
          </span>
          <span>
            GitHub Repo:
            <a href="http://mrklouie.tech/" target="_blank">
              http://mrklouie.tech/
            </a>
          </span>
        </span>
      </body>
    </html>
  );
}
